### ISSUE TITLE
Display the Github repo data of ASF projects

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/Insight#12]
https://github.com/hypertrons/hypertrons-crx/issues/395 defined a data API for project interaction.
We would display the ASF project development activities per month by leveraging these JSON data.

* ic: issue comment count
* oi: open issue count
* op: open pull count
* mp: merge pull count
* rc: review comment count
* ad: merged additions code lines
* de: merged deletions code lines
* s: stars
* f: forks
* p: participants count

You can access the GitHub repo static information just like this
`https://oss.x-lab.info/repo_detail/apache/spark.json`,  
to access another repo data, you can replace 'spark' with another ASF project name.

**Comment by WillemJiang** [comment]
You can get the project activities with interactions of the Github project number.
For more information you can check out the blog 
 https://blog.frankzhao.cn/how_to_measure_open_source_1/

**Comment by roares** [comment]
-  [charts for issue、comments、 pr](https://github.com/WillemJiang/Insight/issues/16)
